name: thor-magni-challenge
channels:
  - conda-forge
dependencies:
  - pip=22.3.1
  - python=3.10.8
  - pip:
    - altair==4.2.0
    - numpy==1.24.1
    - pandas==1.5.3
    - streamlit==1.18.1
    - plotly==5.12.0
    - ray==2.5.1
    - matplotlib
    - tqdm
    - scipy
    - torch
    - torchmetrics
    - matplotlib
    - jupyter